# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticket < Formula
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/DustinReynoldsPE/ticket"
  version "2.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.4.0/ticket_2.4.0_darwin_amd64.tar.gz"
      sha256 "e8b110ad07c4649edf9dde9acb86cd14b8046f9bf75a991205556d3362668082"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.4.0/ticket_2.4.0_darwin_arm64.tar.gz"
      sha256 "625ea944f8710bed8567dda3dc05c73298d81fd5e66dfb8bacaca84b922087e6"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.4.0/ticket_2.4.0_linux_amd64.tar.gz"
      sha256 "d642098fdf2ea70c1fe00cfc07e3710f88ba56a1dc22c678fde2383f96a8d3d1"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.4.0/ticket_2.4.0_linux_arm64.tar.gz"
      sha256 "dc4bd8c9a410853fe345f46f7d2298b389657350a417f7f70f63ad88e81288ed"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end
end
