# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticket < Formula
  desc "Markdown-based ticket management CLI"
  homepage "https://github.com/DustinReynoldsPE/ticket"
  version "2.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.6.0/ticket_2.6.0_darwin_amd64.tar.gz"
      sha256 "be7a71e673b70391c839b8e42969c87cf24e4c7464daa52bd798989ca5407198"

      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.6.0/ticket_2.6.0_darwin_arm64.tar.gz"
      sha256 "eb31f43e895cdd343aab582a7c1dfc39ce7dfc16f67d48c1cd71e3fa1aecd59b"

      define_method(:install) do
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.6.0/ticket_2.6.0_linux_amd64.tar.gz"
      sha256 "1967b3b41878a93f4aa1b1369fcd690057fec08f9b0f17ea3c296b1e31bfcf7f"
      define_method(:install) do
        bin.install "tk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DustinReynoldsPE/ticket/releases/download/v2.6.0/ticket_2.6.0_linux_arm64.tar.gz"
      sha256 "0b123acd581431d06ff63cc58df08b27f0cce3e7a47630cd99dcb4a440150eca"
      define_method(:install) do
        bin.install "tk"
      end
    end
  end
end
